### ISSUE TITLE
swag-cli doesn't configure port

### ISSUE THREAD

**Issue by ffischer1984** [swaggo/gin-swagger#11]
don't know if is a gin or a swag problem
- using gin
- no port declared so gin is using the default port

**Comment by easonlin404** [comment]
Could you post your code?

**Comment by ffischer1984** [comment]
`m.Run()` --> default-port is 8080 but in docs/docs.go stand "host":"localhost" instead of "host":"localhost:8080"

**Comment by ffischer1984** [comment]
it's my fault, sry it was too late yesterday ;)
