### ISSUE TITLE
Is that an bad description about parm type in doc?

### ISSUE THREAD

**Issue by 404cn** [swaggo/gin-swagger#113]
Found this in doc:

![image](https://user-images.githubusercontent.com/24653356/85512301-52ab5d80-b62c-11ea-814d-a87048e36734.png)

Is it should be this or what?

![image](https://user-images.githubusercontent.com/24653356/85512434-7b335780-b62c-11ea-82cc-c1eecf89ea7d.png)

**Comment by ubogdan** [comment]
@404cn if you think the documentation is wrong/broken, please feel free to make us happy with a fix-ing PR.
