### ISSUE TITLE
Could this support swagger3.0

### ISSUE THREAD

**Issue by u2takey** [swaggo/gin-swagger#116]
reopen issue for https://github.com/swaggo/gin-swagger/issues/9

It seems  go-openapi/spec  has no plan to support swagger3.0: https://github.com/go-openapi/spec/issues/21, could we just switch to https://github.com/getkin/kin-openapi for 3.0 support?

**Comment by ubogdan** [comment]
This issue may be addressed in [swag](https://github.com/swaggo/swag) .
