### ISSUE TITLE
Readme guide is not friendly to newer

### ISSUE THREAD

**Issue by Xieyuschen** [swaggo/gin-swagger#127]
&emsp;&emsp;I'm new to gin-swagger with a little backend experience in asp, when I use gin-swagger I found it's easy to misunderstanding the guide in readme for it import a module in github, rather than the local file generated by `swag init`. It really confused me a few hours, luckily I read the example in this repo and finally solve it:)  
&emsp;&emsp;If the guide in readme can tell a newer how to generate its self-define api rather than import `_ "github.com/swaggo/gin-swagger/example/basic/docs"` directly, it can be more friendly to a go-novice:)

**Comment by ubogdan** [comment]
Do you have any suggestions? swagger is an Open Source project and any contribution is welcome. Please feel free to update README by pushing a PR.

**Comment by ubogdan** [comment]
Merged.
