### ISSUE TITLE
go: github.com/ugorji/go@v1.1.5-pre: unknown revision v1.1.5-pre

### ISSUE THREAD

**Issue by mnvx** [swaggo/gin-swagger#128]
Have problem with `go mod download` in project using gin-swagger:

```
go: github.com/ugorji/go@v1.1.5-pre: unknown revision v1.1.5-pre
go: error loading module requirements
```

As I see gin-swagger still use ugorji 1.1.5-pre but this tag is not exists now:

https://github.com/swaggo/gin-swagger/blob/0be48022e8f0d35d979643d8e36032a865cb33f4/go.mod#L13

```
github.com/ugorji/go v1.1.5-pre // indirect
```

This helped me:

```
replace github.com/ugorji/go v1.1.5-pre => github.com/ugorji/go v1.1.7
```

But would be better to update dependencies in this project. Thanks.

**Comment by ugorji** [comment]
Hi. ugorji author here. This was my mistake. The v1.1.5-pre tag was a pre-release tag that I used to test out how to implement modules robustly. I was confident (incorrectly) that no one was using it. I have not found a way to restore the tag. 

Please please - update to a more recent version, preferably github.com/ugorji/go/codec v1.1.12 or later.

**Comment by rifki** [comment]
+1

Same problem here

**Comment by rifki** [comment]
"Please please - update to a more recent version, preferably github.com/ugorji/go/codec v1.1.12 or later."
@ugorji I think you still need update `go.mod`. because in my case we still blocking downloading `v1.1.5-pre`.

please help.

**Comment by ugorji** [comment]
> +1
> 
> Same problem here

What problem are you having? The prior issue should be resolved - see https://github.com/ugorji/go/tree/v1.1.5-pre , though I still believe we should upgrade to a recent version (currently v1.1.13).

**Comment by rifki** [comment]
> > +1
> > Same problem here
> 
> What problem are you having? The prior issue should be resolved - see https://github.com/ugorji/go/tree/v1.1.5-pre , though I still believe we should upgrade to a recent version (currently v1.1.13).

@ugorji 
I think google cloud cannot fetch the tag version v1.1.5-pre.

Here is the detail in our server(Google app engine)
```
Error Response: [9] Cloud build d78c5d09-7a03-42b8-8ff8-4dffc1596847 
status: FAILURE
Error ID: ce990988
Error type: UNKNOWN
Error message: 
go: finding github.com/mattn/go-isatty v0.0.7
go: finding github.com/json-iterator/go v1.1.6
go: finding github.com/gin-contrib/sse v0.0.0-20190301062529-5545eab6dad3
go: finding github.com/ugorji/go/codec v1.1.12
go: finding github.com/ugorji/go v1.1.4
go: finding github.com/golang/protobuf v1.3.1
go: finding github.com/ugorji/go/codec v1.1.5-pre
go: finding github.com/kr/pty v1.1.1
go: finding github.com/google/go-cmp v0.4.0
go: finding golang.org/x/net v0.0.0-20180218175443-cbe0f9307d01
go: finding golang.org/x/net v0.0.0-20190503192946-f4e77d36d62c
go: finding google.golang.org/protobuf v1.23.0
**go: github.com/ugorji/go/codec@v1.1.5-pre: unknown revision codec/v1.1.5-pre**
go: error loading module requirements
```

any suggestion?

**Comment by ugorji** [comment]
That's surprising. i can see it on pkg.go.dev
https://pkg.go.dev/github.com/ugorji/go/codec@v1.1.5-pre

I can also see it here: https://proxy.golang.org/github.com/ugorji/go/codec/@v/v1.1.5-pre.info which returns
```
{"Version":"v1.1.5-pre","Time":"2019-05-28T08:31:36Z"}
```

So - I don't have any good suggestions. Hopefully one of the developers here can just update their dependencies, or you can do a `go get -u github.com/swaggo/gin-swagger` and see if that resolves your dependencies issue.
