### ISSUE TITLE
Steps for win 10?

### ISSUE THREAD

**Issue by ffischer1984** [swaggo/gin-swagger#13]
this works: go get github.com/swaggo/swag/cmd/swag 
but the swag-command doesn't work in the windows-cmd

for these both i get an error:
go get -u github.com/swaggo/gin-swagger --> package github.com/swaggo/gin-swagger: remote origin not found

go get -u github.com/swaggo/gin-swagger/swaggerFiles --> go get -u github.com/swaggo/gin-swagger/swaggerFiles

and internet is working

**Comment by easonlin404** [comment]
please download the swag binary [v1.4.1](https://github.com/swaggo/swag/releases/tag/v1.4.1) for windows.
