### ISSUE TITLE
Static check for basic rules to make sure code & documentation is in sync.

### ISSUE THREAD

**Issue by moqmar** [swaggo/gin-swagger#143]
For CI usage, it would be awesome if there was a command that could detect from where a documented method is called (`.GET("...", ..., MyFunction)`), if method & path matches the documentation, as well as if all path parameters are documented. Also, it could check if all statically used parameters, query string arguments etc. (like `c.Param("...")`) are documented.

This obviously gets a bit more complex when groups etc. come into play, but even a simple implementation would be a huge improvement that would ensure consistency between code and documentation.

**Comment by ubogdan** [comment]
@moqmar The idea sounds very interesting but this is something out of scope from Swagger's perspective.
