### ISSUE TITLE
How to use slice and map?

### ISSUE THREAD

**Issue by kay07** [swaggo/gin-swagger#149]
As we know,gin can use slice and map,just like c.QueryArray and c.QueryMap,but I don't know how to add it to the swag ，just like "// @Param env query map false "env".
Thanks!

**Comment by ubogdan** [comment]
I can bet you didn read the [documentation](https://github.com/swaggo/swag/blob/master/operation_test.go#L1216) or the [code](https://github.com/swaggo/swag/blob/master/operation_test.go#L1216). 

Try
```
// @Param env query []string false "Some description"`
```
