### ISSUE TITLE
Cannot use ginSwagger.WrapHandler(swaggerFiles.Handler) ...

### ISSUE THREAD

**Issue by EDDYCJY** [swaggo/gin-swagger#16]
1、`main.go` file: 
```
package main

import (
	"fmt"
	"net/http"

	"xxx/routers"
	"xxx/setting"
)

func main() {
	router := routers.InitRouter()

	s := &http.Server{
		Addr:           fmt.Sprintf(":%d", setting.HTTPPort),
		Handler:        router,
		ReadTimeout:    setting.ReadTimeout,
		WriteTimeout:   setting.WriteTimeout,
		MaxHeaderBytes: 1 << 20,
	}

	s.ListenAndServe()
}
```

2、`router.go` file: 
```
package routers

import (
    "github.com/gin-gonic/gin"
    "github.com/swaggo/gin-swagger"
    "github.com/swaggo/gin-swagger/swaggerFiles"

    _ "xxx/docs"
)

func InitRouter() *gin.Engine {
    r := gin.New()

    r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

    return r
}
```

3、execute the following command, an error occurs
```
$ go run main.go 
routers/router.go:26:50: cannot use ginSwagger.WrapHandler(swaggerFiles.Handler) (type "github.com/gin-gonic/gin".HandlerFunc) as type "xxx/vendor/github.com/gin-gonic/gin".HandlerFunc in argument to r.RouterGroup.GET
```

**Comment by pei0804** [comment]
I could not reproduce it.
I think to your gin is old.

**Comment by easonlin404** [comment]
It seems like your go program use wrong $GOPATH to catch gin package
```
xxx/vendor/github.com/gin-gonic/gin
```

**Comment by EDDYCJY** [comment]
@pei0804 @easonlin404 I solved this problem after updating gin , tk

**Comment by EDDYCJY** [comment]
If there is a requirement on the version, it is recommended to explain in README.MD ?

**Comment by pei0804** [comment]
Bay the way, What was your version?

**Comment by BellUser** [comment]
I am having the same issue with Gin 1.2.

**Comment by jttttttttttttt** [comment]
I am having the same issue with Gin 1.3.

**Comment by jttttttttttttt** [comment]
routers\routers.go:22:53: cannot use ginSwagger.CustomWrapHandler(config, swaggerFiles.Handler) (type "github.com/gin-gonic/gin".HandlerFunc) as type "GinSample/vendor/github.com/gin-gonic/gin".HandlerFunc in argument to
 r.RouterGroup.GET

**Comment by jttttttttttttt** [comment]
I use govendor  to init my project, so in my project dir will create vendor pkg and will put gin project in this pkg. Finally，I move gin-swagger in this pkg.

**Comment by vzool** [comment]
@easonlin404 and @pei0804 Hi, why you don't push a new "**git tag**" so `go module` can pull the latest version everywhere?

**Comment by girishgupta211** [comment]
```
go get -u github.com/gin-gonic/gin
govendor add +e
```
