### ISSUE TITLE
How can declare route swagger without *any? it's not allow on AWS

### ISSUE THREAD

**Issue by umiatiyah** [swaggo/gin-swagger#166]
is it possible to declare route like :
r.GET("/swagger/docs", ginSwagger.WrapHandler(swaggerFiles.Handler))

and just call on URL like : 
localhost:8080/swagger/docs 
without add index.html on URL but auto go to page index.html ?

route "swagger/*any" not allow when i create resource on AWS

**Comment by ubogdan** [comment]
Did you figure it out? 
Can you share with us so other users may benefit from your findings?

**Comment by davidkhala** [comment]
I have similar question, and is there anyway we can make redirect?

**Comment by dud225** [comment]
Here is what I use to automatically redirect to `/index.html`:
```golang
        swaggerHandlerFunc := func(c *gin.Context) {
          if c.Param("any") == "/" {
            c.Redirect(http.StatusMovedPermanently, "/swagger/index.html")
            return
          }
          ginSwagger.WrapHandler(swaggerFiles.Handler)(c)
        }
        r.GET("/swagger/*any", swaggerHandlerFunc)
```

The `any` parameter is necessary but actually it doesn't need to be called `any`, any other name is also valid:
```golang
r.GET("/swagger/*random", swaggerHandlerFunc)
```

**Comment by samuelv8** [comment]
> Here is what I use to automatically redirect to `/index.html`:
> 
> ```go
>         swaggerHandlerFunc := func(c *gin.Context) {
>           if c.Param("any") == "/" {
>             c.Redirect(http.StatusMovedPermanently, "/swagger/index.html")
>             return
>           }
>           ginSwagger.WrapHandler(swaggerFiles.Handler)(c)
>         }
>         r.GET("/swagger/*any", swaggerHandlerFunc)
> ```
> 
> The `any` parameter is necessary but actually it doesn't need to be called `any`, any other name is also valid:
> 
> ```go
> r.GET("/swagger/*random", swaggerHandlerFunc)
> ```

Somehow this won't work if there's a path prefix (e.g. `/v1`)

**Comment by jm-janzen** [comment]
Even simpler, you can do

```go

router.GET("/", func(c *gin.Context) {
		c.Redirect(http.StatusPermanentRedirect, "/swagger/index.html")
	})
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
```

But I wish I could just serve swagger docs from a custom URL, rather than having to redirect...
