### ISSUE TITLE
Conceptual understanding

### ISSUE THREAD

**Issue by BenWolfaardt** [swaggo/gin-swagger#173]
Dear team, 

thanks for quickly having helped me with my previous issue, I've managed to successfully implement your solution for my use case, using an already defined `openapi.yaml` file. 

I, however, have a question that took me quite a while to figure out and that I'd like to understand 🤓

In your example in your [README.md](https://github.com/swaggo/gin-swagger/blob/master/README.md) you have the following snippet of code:
```go
func main()  {
   r := gin.Default()
   docs.SwaggerInfo.BasePath = "/api/v1"
   v1 := r.Group("/api/v1")
   {
      eg := v1.Group("/example")
      {
         eg.GET("/helloworld",Helloworld)
      }
   }
   r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
   r.Run(":8080")

}
```

My question is why does the 
```go 
r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
```
need to be outside of the `vi` group, why is it that when I coded it, as below, I kept getting various errors:
```go
func main()  {
   r := gin.Default()
   docs.SwaggerInfo.BasePath = "/api/v1"
   v1 := r.Group("/api/v1")
   {
      eg := v1.Group("/example")
      {
         eg.GET("/helloworld",Helloworld)
      }
	  swagger := v1.Group("/swagger")
	  {
		 swagger.GET("/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
	  }
   }
   r.Run(":8080")

}
```
Furthermore, it didn't allow port: `8080` to be "published", i.e. I wasn't able to access it with localhost:8080 when the `swagger.GET("/*any", ginSwagger.WrapHandler(swagger files.Handler))` line of code was in it's new position. 

I assumed that there might be a "concurrency" issue and I thus ran it as a separate `goroutine` which allowed it to now expose port `8080`, however, now I was getting a panic:
```
catch-all conflicts with existing handle for the path segment root in the path...`
```
I was able to get rid of the panic by removing the `/*any` from the `GET` command, but now when accessing http://localhost:8080/swagger/index.html I would only have a blank page, not a `404`, but still not able to access the Swagger. 

After wanting to reconfigure my sandbox system, I was re-checking your documentation when I noticed that you had 
```go
 r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
 ```
Outside of the `Group`.

I then quickly was able to solve my problem and implemented the solution into our more complex system (without the need for the `goroutine` or having to remove the `/*any` command), however, I don't understand why it can't work like that?

Please note that I am very new to `Go` as well as being a developer, so any insight would be appreciated to help with my fundamental understanding of the system. 

Thanks in advance and kind regards :)

**Comment by ubogdan** [comment]
What exactly is not working here ? 
With the code below  I can access the documentation at the following URL http://localhost:8080/api/v1/swagger/index.html
```
package main

import (
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/swaggo/gin-swagger/example/basic/docs"
)

func main()  {
	r := gin.Default()
	v1 := r.Group("/api/v1")
	{
		eg := v1.Group("/example")
		{
			eg.GET("/helloworld",func(*gin.Context) {})
		}
		swagger := v1.Group("/swagger")
		{
			swagger.GET("/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
		}
	}
	r.Run(":8080")

}
```

**Comment by BenWolfaardt** [comment]
Thanks @ubogdan for your quick response, 

I've tried recreating the issue with your assistance and seem to have found the problem, still don't understand it though, but I'll try to explain it here so that you could perhaps explain what's happening. 

If I run the code as per the below:

```go
{
	  s := GinServer{
		    q:                            opts.MessageQueue,
		    processRepo:                  opts.ProcessRepository,
		    paginator:                    pagination.NewDatabasePaginator(),
		    bastionService:               opts.BastionService,
		    chainCtrl:                    opts.ChainController,
		    skipEIdentityCheckMiddleware: opts.SkipEIdentityCheckMiddleware,
			skipOIDCMiddleware:           opts.SkipOIDCMiddleware,
	  	}
	  
	  	...
	  
	  	s.r = gin.New()
	  
	  	....
	  
	 	apiGroup := s.r.Group("/api")
		{
			v1Group := apiGroup.Group("/v1")
			{
				v1WalletGroup := v1Group.Group("/wallet")
				{
					transfersGroup := v1WalletGroup.Group("/transfers")
					{
						...
					}
		 			...
				}
	  
				v1ShareDocGroup := v1Group.Group("/sharedoc")
				{
					...
				}
	  
				...
	  
				v1SwaggerGroup := v1Group.Group("/swagger")
				{
					v1SwaggerGroup.StaticFile("/swagger/openapi.yaml", "./swagger/openapi.yaml")
					v1SwaggerGroup.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.URL("/swagger/openapi.yaml")))
				}
			}
		}
	...
}
```

I get the following `panic`:

```go
func (n *node) insertChild(path string, fullPath string, handlers HandlersChain) {
	...
	if len(n.path) > 0 && n.path[len(n.path)-1] == '/' {
		panic("catch-all conflicts with existing handle for the path segment root in path '" + fullPath + "'")
	}
	...
}
```

Which is inside: `/.../go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/tree.go`

However, if I simply change the `v1SwaggerGroup` as follow it works: 

```go
	  v1SwaggerGroup := v1Group.Group("/swagger")
	  {
		  v1Group.StaticFile("/swagger/openapi.yaml", "./swagger/openapi.yaml")
		  v1SwaggerGroup.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.URL("/swagger/openapi.yaml")))
	  }
```

and I don't understand why mentioning the `StaticFiles` in a "lower" level URL path that it works?

Any insights would be appreciated. 

Kind regards, 
Ben

**Comment by BenWolfaardt** [comment]
Thanks for all of your help, I realised that the issue I was having was a result of our systems `authentication middleware`.
