### ISSUE TITLE
Can you support changing skin?

### ISSUE THREAD

**Issue by lshsuper** [swaggo/gin-swagger#191]

**Comment by ubogdan** [comment]
@lshsuper, Our main scope is to provide a basic UI that can serve as a view-er and testing interface for the generated documentation.

The UI served by the gin-swagger handler is based on [swagger-ui](https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/). Please visit the link above and let us know if you find something useful.

**Comment by ubogdan** [comment]
@ish
