### ISSUE TITLE
localhost:8080/swagger returns 404 page not found

### ISSUE THREAD

**Issue by SejalAbhangrao** [swaggo/gin-swagger#2]
Doc folder gets created with doc.go file however I am unable to find anything on localhost:8080/swagger. Could you please help?

**Comment by easonlin404** [comment]
@SejalAbhangrao could you post your `main.go` file?

**Comment by easonlin404** [comment]
@SejalAbhangrao document were wrong. You have to browser to http://localhost:8080/swagger/index.html
<img width="1438" alt="2017-10-24 8 27 02" src="https://user-images.githubusercontent.com/8943871/31943004-dd08a10e-b88c-11e7-9e77-19d2c759a586.png">

**Comment by SejalAbhangrao** [comment]
Thank you so much for solving it. I can see the same page as index.html. But then why don't my changes get reflected there?  My doc.go file has different structure than the one mentioned in index.html. Could you please help me understand ?

**Comment by SejalAbhangrao** [comment]
Your project has helped me a lot so far. However I am struggling at one point. My APIs have both the GET and POST method for the same endpoint. But the swagger documentation that gets created only displays the second one (I wrote annotations for GET method and then POST. So swagger only displays the POST one). Could you help me solve it? :)

**Comment by easonlin404** [comment]
@SejalAbhangrao  Can you post your actual code to understand better ?

**Comment by JeHwanYoo** [comment]
```
	r.GET("/swagger/*any", func(c *gin.Context) {
		if c.Request.RequestURI == "/swagger/" {
			c.Redirect(302, "/swagger/index.html")
			return
		}
		ginSwagger.WrapHandler(swaggerFiles.Handler)(c)
	})
```
