### ISSUE TITLE
无法通过post提交json格式数据，只能是form格式的？？？

### ISSUE THREAD

**Issue by 627886474** [swaggo/gin-swagger#20]
求解答

**Comment by easonlin404** [comment]
Can you post your code to reproduce issue? And please use English to let other people can understand.

**Comment by jony-lee** [comment]
of cause it can, you just set like
`// @Accept  json`
`// @Param   -   body    model.StructReq     false  " "`
where `-` is a placeholder.

**Comment by lookCLZ** [comment]
please use english  @627886474

**Comment by 627886474** [comment]
I made a mistake!
thank you for answer
