### ISSUE TITLE
I want support go version:1.18

### ISSUE THREAD

**Issue by 1121076248** [swaggo/gin-swagger#201]
I want support go version:1.18

**Comment by ubogdan** [comment]
😄 Do you have any issue with gin on go 1.18?

**Comment by 1121076248** [comment]
![image](https://user-images.githubusercontent.com/19721126/162101573-7863247e-74e5-4253-915c-8e982f2cf9d9.png)
![image](https://user-images.githubusercontent.com/19721126/162101629-f1386e88-7828-4117-95a5-8b1bba344c1a.png)
The new feature does not appear to be supported

**Comment by ubogdan** [comment]
This issue is not related to gin. 

Duplicated https://github.com/swaggo/swag/issues/1170
