### ISSUE TITLE
cannot find type definition: errors.NewError

### ISSUE THREAD

**Issue by shumintao** [swaggo/gin-swagger#229]
- wrong message 

```
╰─± swag init
2022/08/17 16:10:43 Generate swagger docs....
2022/08/17 16:10:43 Generate general API Info, search dir:./
2022/08/17 16:10:43 ParseComment error in file /Users/taoshumin_vendor/go/src/test.io/wsm/server/http_server_ctl.go :cannot find type definition: errors.NewError

```

- swag version

```
╰─± swag -version
swag version v1.8.1
```

- swagger 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/26895243/185073642-ae06c8ce-1bec-4f88-b7a3-dc9daeefb96e.png">

- tree

```
╰─± tree
.
├── README.md
├── cmd
│   ├── openurl_unix.go
│   ├── openurl_windows.go
│   ├── root.go
│   ├── server.go
│   ├── upgrade
│   │   └── upgrade.go
│   └── upgrade.go
├── core
│   ├── client.go
│   ├── client_test.go
│   └── istio.go
├── docs
│   ├── docs.go
│   ├── swagger.json
│   └── swagger.yaml
├── errors
│   ├── doc.go
│   ├── errors.go
│   └── errors_test.go
├── go.mod
├── go.sum
├── log
│   ├── log.go
│   └── log_test.go
├── main.go
├── render
│   ├── mock
│   │   ├── errors
│   │   │   └── errors.go
│   │   └── render.go
│   └── render.go
├── server
│   ├── error.go
│   ├── http_api.go
│   ├── http_server_ctl.go
│   ├── http_server_mesh.go
│   ├── http_server_ws.go
│   ├── middleware_cors.go
│   ├── middleware_realip.go
│   ├── middleware_recoverer.go
│   ├── middleware_request_id.go
│   ├── middleware_skip_options.go
│   ├── server.go
│   └── server_test.go
└── services
    ├── controller.go
    ├── controller_test.go
    ├── dr
    │   ├── cache.go
    │   └── handler.go
    ├── gw
    │   ├── cache.go
    │   └── handler.go
    ├── informer.go
    └── vs
        ├── cache.go
        └── handler.go

```

- render

<img width="544" alt="image" src="https://user-images.githubusercontent.com/26895243/185073912-7877f6cc-5535-47ac-8afc-fa0c140c7956.png">

- errors 

<img width="551" alt="image" src="https://user-images.githubusercontent.com/26895243/185073978-1b6b25b0-9f25-49ca-aff7-85559ff7cb70.png">

**Comment by ubogdan** [comment]
You need to describe what the response would look like.

 Try `@success 200 {object} errors.Error`

**Comment by shumintao** [comment]
> Error

Still having questions?

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/26895243/185086398-591669db-eeda-4b0d-8a02-c03cd681aaf7.png">

**Comment by shumintao** [comment]
> You need to describe what the response would look like.
> 
> Try `@success 200 {object} errors.Error`

```
	_ "yho.io/wsm/errors"
```

Doing this will compile the past.
```
	Err  error `json:"-"`
```

**Comment by shumintao** [comment]
> You need to describe what the response would look like.
> 
> Try `@success 200 {object} errors.Error`

There seems to be a problem with introducing an external third party?

<img width="503" alt="image" src="https://user-images.githubusercontent.com/26895243/185092377-b3a490ab-f041-4f6c-bfc1-aeac20efd0c2.png">

```
± swag init --parseDependency --parseInternal
2022/08/17 17:58:52 Generate swagger docs....
2022/08/17 17:58:52 Generate general API Info, search dir:./
2022/08/17 17:58:52 Generating errors.Error
2022/08/17 17:58:52 ParseComment error in file /Users/taoshumin_vendor/go/src/test.io/wsm/server/http_server_mesh.go :missing required param comment parameters "data body v1alpha3.Gateway"
```

**Comment by ubogdan** [comment]
Try to alias the import.

**Comment by shumintao** [comment]
> alias

alias  don't seem to work.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/26895243/185113271-9ec3f8c3-eb47-40af-be1a-794761c1c0b3.png">

**Comment by shumintao** [comment]
> Try to alias the import.

swag init --parseDependency -g main.go

this way can solve  .

**Comment by shumintao** [comment]
> Try to alias the import.

May I ask you another question? How to write struct generics? Why do I write an error like this?

```
type SortConstraint interface {
	*v1alpha3.Gateway | *v1alpha3.DestinationRule | *v1alpha3.VirtualService
}

type oldestFirst[T SortConstraint] []*T

func (q oldestFirst[T]) Len() int { return len(q) }
func (q oldestFirst) Less(a, b int) bool {
	return q[a].CreationTimestamp.Time.After(q[b].CreationTimestamp.Time)
}
func (q oldestFirst) Swap(a, b int) { q[a], q[b] = q[b], q[a] }

```

<img width="750" alt="image" src="https://user-images.githubusercontent.com/26895243/185522605-81f0fe2b-2a20-46b9-a153-73ba2b80ea34.png">

**Comment by ubogdan** [comment]
The generics support is in the early stage of development. Not sure if it's possible. Anyway, you need to describe a response object and you can better use a DTO for that.
