### ISSUE TITLE
Unable to load doc.json

### ISSUE THREAD

**Issue by xrwang8** [swaggo/gin-swagger#230]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/68765051/185726273-622cb4b9-f8f0-460e-80ac-f1c2c516d5dd.png">

<img width="958" alt="image" src="https://user-images.githubusercontent.com/68765051/185726300-7d3a8ff7-77ad-46ba-92f9-fe42f1d03e0e.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/68765051/185726303-c28197cc-1227-46ae-8c5b-a33fa8252ecf.png">

**Comment by xrwang8** [comment]
Sorry, I forgot to import the doc document

**Comment by Cprakhar** [comment]
> Sorry, I forgot to import the doc document

How did you fixed this error, can you provide the code @xrwang8.


Here are my code files:
`http.go`
<img width="723" height="271" alt="Image" src="https://github.com/user-attachments/assets/2db10c02-e9f8-4e2f-af2c-a3822781299d" />

`main.go`
<img width="1119" height="629" alt="Image" src="https://github.com/user-attachments/assets/931bcaed-c27a-4def-ad44-42a856ff70b9" />

I am importing the mount and run func in the `main.go` to mount and start the server.
