### ISSUE TITLE
Authorization Code with PKCE

### ISSUE THREAD

**Issue by SudoSpartanDan** [swaggo/gin-swagger#243]
Is there a way to set up an Authorization Code flow with PKCE? Trying to get my generated Swagger UI to work with Okta, which requires PKCE.

**Comment by thalionath** [comment]
Hi @ubogdan
Do you have time to review my PR to close this?
Cheers

**Comment by mriddell-foundry** [comment]
Wondering if there is any update to merging the linked PR? Currently making the changes locally to get around this
