### ISSUE TITLE
How do I add description in model then show in sawgger?

### ISSUE THREAD

**Issue by JimChung0403** [swaggo/gin-swagger#25]
I hope  to look at the description in sawgger (like picture).
How can I do write struct?

type ExamplePost struct {
    Name string `binding:"required" example:"jim"`
    Old int `binding:"required" example:"30" format:"int"`
}

![image](https://user-images.githubusercontent.com/13103974/41394147-80fccf3c-6fdb-11e8-91e7-b94600cc0c2a.png)

**Comment by cyrinux** [comment]
Hi @JimChung0403 have you find how to do?

**Comment by JimChung0403** [comment]
@cyrinux 
I don't find how to do.
please help me. thank you very much.

**Comment by cyrinux** [comment]
@JimChung0403 I search too sorry ;)

**Comment by nzlov** [comment]
Try:
```
type Pet struct {
   // ID this is petid
   ID       int `json:"id"`
}
```

**Comment by easonlin404** [comment]
please reopen it if still have questions.
