### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by rcorre** [swaggo/gin-swagger#26]
For those using a dependency manager ([dep](https://github.com/golang/dep), [glide](https://glide.sh/), ect.), it would be nice to pin to a tagged release rather than a random commit.

It seems like this project has been around for over a year and developed a fair bit of interest, is it time for an official release?

**Comment by easonlin404** [comment]
Thank you for your interest in, we have added v.1.0.0 tag!!   🎉
