### ISSUE TITLE
can gin-swagger display the model structs with default order

### ISSUE THREAD

**Issue by godcong** [swaggo/gin-swagger#42]
example in swagger:
model.Menu{
active	string
description	string
icon	string
id	string
name	string
pid	string
slug	string
sort	integer
url	string
}

define in struct:
        ID         string
	PID         string
	Name        string
	Icon        string
	Slug        string
	URL         string
	Active      string
	Description string
	Sort        int

it's not the same orders
how can i set to display in swagger with the same order with struct define

**Comment by godcong** [comment]
too long time no result

**Comment by Jagerente** [comment]
In case some one is still looking for solution.
You have to add `extensions:"x-order=N"` tag next to the field:

```golang
type Character struct {
	Name           map[languages.Language]string `json:"name" extensions:"x-order=0"`
	Description    map[languages.Language]string `json:"desctiption" extensions:"x-order=1"`
        // etc...
}
```
