### ISSUE TITLE
Operations tag other than default

### ISSUE THREAD

**Issue by benkauffman** [swaggo/gin-swagger#44]
Is there a way to create an operations tag other than _default_?
<img width="1213" alt="Screen Shot 2019-03-19 at 11 37 47 AM" src="https://user-images.githubusercontent.com/16448205/54632491-76502300-4a3b-11e9-8c6a-790e1aa6c160.png">

Would be ideal for me to have _auth_ & _user_ operation groups.

**Comment by jiangfan233** [comment]
use @tags
