### ISSUE TITLE
Can not find ref type

### ISSUE THREAD

**Issue by zzq392342084** [swaggo/gin-swagger#5]
when use Type from external package ,It output error,
for example ,when reference gogs.CreateOrgOption from gopath,error occur:
ParseComment panic:Can not find ref type:"gogs.CreateOrgOption".

**Comment by easonlin404** [comment]
ref:
https://github.com/swaggo/swag/issues/16
https://github.com/swaggo/swag/issues/17

**Comment by easonlin404** [comment]
`Swag` now only search in project root folder which contains main.go file (https://github.com/swaggo/swag/issues/16#issuecomment-348101999). Thanks. 😄
