### ISSUE TITLE
Default URL value for configuration should not be hardcoded to localhost

### ISSUE THREAD

**Issue by cshong0618** [swaggo/gin-swagger#50]
Since the addition of configuration while creating a handler, the default value of `defaultConfig.URL` will break all services that has a custom hostname. 

Through experiments, using `swagger/doc.json` would be a better default url than `http://localhost:8080/swagger/doc.json`.

**Comment by easonlin404** [comment]
Linked will open new windows no matter using `swagger/doc.json` or `doc.json`. Please use #52 or `CustomWrapHandler(config, swaggerFiles.Handler)` func to set URL value.

**Comment by cshong0618** [comment]
Tested and works. Thank you.
