### ISSUE TITLE
Param description length limit

### ISSUE THREAD

**Issue by locxiang** [swaggo/gin-swagger#51]
The content of the description will be intercepted

![image](https://user-images.githubusercontent.com/6622033/55059505-10eada80-50aa-11e9-849e-a3de64429716.png)

![image](https://user-images.githubusercontent.com/6622033/55059525-1fd18d00-50aa-11e9-8c09-5771368a252b.png)

**Comment by ubogdan** [comment]
I hope you figured it out. The comment is a simple text that the developer uses to instruct the API user what that parameter does. 

I don't see any issue/bug here.
