### ISSUE TITLE
please adapt gin@v1.4.0

### ISSUE THREAD

**Issue by lxzan** [swaggo/gin-swagger#59]

**Comment by lxzan** [comment]
it will be conflectted in gin@v1.4.0 project using gin-swagger. Gin and gin-swagger relay on different version of  a package.

**Comment by easonlin404** [comment]
I will tidy up dependencies asap.

**Comment by easonlin404** [comment]
fixed by #60

**Comment by jixiuf** [comment]
how about release a new version
