### ISSUE TITLE
not support struct's field  is interface or json.RawMessage ?

### ISSUE THREAD

**Issue by Cloudzp** [swaggo/gin-swagger#62]
I defined a struct with fields type is interface or json.RawMessage, when i exec command `swag init` ,i get some error: " Something goes wrong: &ast.InterfaceType{Interface:296, Methods:(*ast.FieldList)(0xc00029bd10), Incomplete:false}"
my struce ：
```
type RespBody struct {
	RequestID string          `json:"request_id"`
	Message   string          `json:"message"`
	Code      int             `json:"code"`
	ErrorCode string          `json:"error_code,omitempty"`
	Data     interface{} `json:"data,omitempty"`
}
```
this is a bug? can you fix this ? thank you very much!

**Comment by wuzheng0709** [comment]
how to fix it?
