### ISSUE TITLE
How to remove example API？

### ISSUE THREAD

**Issue by hack-fang** [swaggo/gin-swagger#63]
info:
go:1.12
GO112MODULE=on

As the picture shows， how do not show example api?

# ![example-api](https://user-images.githubusercontent.com/12555752/60231186-00c1e180-98cb-11e9-9120-0c5f9708520e.png)

**Comment by BigbigY** [comment]
+1

**Comment by easonlin404** [comment]
Would you post your `main.go` that includes `doc` generated by swag?

**Comment by lzz001** [comment]
> info:
> go:1.12
> GO112MODULE=on
> 
> As the picture shows， how do not show example api?
> 
> # ![example-api](https://user-images.githubusercontent.com/12555752/60231186-00c1e180-98cb-11e9-9120-0c5f9708520e.png)

I have the same problem, have you solved it
