### ISSUE TITLE
Is this syntax not supported now ？   @Success 200 {string} json "{"code":200,"data":{},"msg":"ok"}"

### ISSUE THREAD

**Issue by lookCLZ** [swaggo/gin-swagger#84]
Is this syntax not supported now ？
```
@Success 200 {string} json "{"code":200,"data":{},"msg":"ok"}"
```

**Comment by jerrylocker** [comment]
the same problem：
```
 ParseComment error in file x\y.go :can not find schema type: "z.json"
```
go version go1.13.4 windows/amd64
github.com/gin-gonic/gin v1.4.0
github.com/swaggo/gin-swagger v1.2.0
github.com/swaggo/swag v1.5.1

**Comment by ubogdan** [comment]
This issue is not related to middleware. Please open it on [swag](https://github.com/swaggo/swag/issues).
