### ISSUE TITLE
Could this support swagger3.0?

### ISSUE THREAD

**Issue by victor-simida** [swaggo/gin-swagger#9]
hi,thank you for your extension here, i want to generate swagger 3.0 docs, is this support?

**Comment by victor-simida** [comment]
maybe i could use this to convert
https://blog.runscope.com/posts/tutorial-upgrading-swagger-2-api-definition-to-openapi-3

**Comment by easonlin404** [comment]
@victor-simida Because `swag` uses [go-openapi/spec](https://github.com/go-openapi/spec) to the 2rd docs and we will prepare to support swagger v3.0 asap if https://github.com/go-openapi/spec/ has supported the 3rd ready(ref https://github.com/go-openapi/spec/issues/21). 😄
