### ISSUE TITLE
Can't use / as router path

### ISSUE THREAD

**Issue by circa10a** [swaggo/gin-swagger#95]
When specifying the root context as a path like so:

```
// @Router / [post]
```

I get the following:

```
❯ swag init
2019/12/18 11:09:51 Generate swagger docs....
2019/12/18 11:09:51 Generate general API Info, search dir:./
2019/12/18 11:09:51 ParseComment error in file routes.go :can not parse router comment "/ [post]"
```

Is this expected behavior? Surely this has been hit before?

**Comment by ubogdan** [comment]
Please open an issue on [swag](https://github.com/swaggo/swag) because it's not related to the HTTP handler.
