### ISSUE TITLE
Can't generate spec from different folder than main.go

### ISSUE THREAD

**Issue by LuD1161** [swaggo/gin-swagger#99]
## Problem statement
Hello,
Having this issue - No operations defined in spec!

## What I've found till now 
I have my package in a different directory from where I have my `main.go` and so `swag init` isn't able to generate the docs for annotations from those files.
Output of `tree`
![image](https://user-images.githubusercontent.com/17861054/74367457-e86deb00-4df7-11ea-8568-691bf649bbbe.png)

## Environment
go version: 1.13
OS:   Linux

Similar to #64

**Comment by ubogdan** [comment]
On to of the tree run `swag init -g cmd/tnbt/main.go`

**Comment by LuD1161** [comment]
@ubogdan thanks for the prompt reply. But that doesn't seem to help.
<img width="543" alt="image" src="https://user-images.githubusercontent.com/17861054/74403483-54c70980-4e4d-11ea-85b4-89923f169568.png">

**Comment by LuD1161** [comment]
Found my mistake. Forgot to add the `// @Router /user/{id} [get]`
Thanks @ubogdan
